### PR TITLE
using eth_getBlockReceipts for faster syncing

### PR DESCRIPTION
**Pull request by bufrr**
Using `eth_getBlockReceipts` will be much faster than get tx receipts one by one

### CODE REVIEW

**Comment by RogerPodacter** [comment]
Thanks! Question: does this have wide enough support for it to be the only method? I feel like I read it wasn't part of the "official" API. Should we support the "old way" as well?

**Comment by bufrr** [comment]
Hi, I think the "old way" will never catch up to the latest block; sending up to 200-300 requests for syncing within 12 seconds (block interval) seems impossible.
Most RPC providers, like alchemy quicknode blastapi, etc., support  `eth_getBlockReceipts`, so I think maybe I can support batch requests to support the "old way" later. ' eth_getBlockReceipts is the best solution for non-alchemy clients for now.

**Comment by bufrr** [comment]
> Thanks! Question: does this have wide enough support for it to be the only method? I feel like I read it wasn't part of the "official" API. Should we support the "old way" as well?

Hi, I think the "old way" will never catch up to the latest block; sending up to 200-300 requests for syncing within 12 seconds (block interval) seems impossible.
Most RPC providers, like alchemy quicknode blastapi, etc., support eth_getBlockReceipts, so I think maybe I can support batch requests to support the "old way" later. ' eth_getBlockReceipts is the best solution for non-alchemy clients for now.

**Comment by RogerPodacter** [comment]
Ok I like it! Have you tested this on a real client? Is there a way I can?

**Comment by bufrr** [comment]
> Ok I like it! Have you tested this on a real client? Is there a way I can?

I use this PR to sync on my client, which works fine. You can just use the universal client with Alchemy API

**Comment by RogerPodacter** [comment]
I love it! Merged!

**Pull request merged**
