### PR TITLE
Support gzip in content uris of ethscriptions created from calldata

### PR DESCRIPTION
**Pull request by RogerPodacter**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@RogerPodacter 

Does that mean we gzip the data uri (eg, for image data:image/png;base64,<data>), or the file directly?

If it is the file directly.. that kinda sucks. It is good that we can skip the 33% from b64, but just think about how the tracking/indexing will become even harder.

Like, okay, if i detect the `0x1f8b` in the input calldata, then what? How i can know what and how to serve it? Or infer more metadata from it like the mimetype and etc?

**Comment by tunnckoCore** [comment]
> This ESIP does not apply to contract-created ethscriptions or ethscription transfers

Also, what's the problem to be supported on contracts creation too? It's basically the same thing? Sure, contracts cannot gzip (i think?), but we usually can use contract-based creation by passing the calldata to the "mint method". Thus, we can pass gzipped data too.

Also, why not support gzipping transfers too? Lets open an ESIP for that too. And for Bulk contract transferring.

**Comment by tunnckoCore** [comment]
Also, what i'm seeing is that the (uint8array/arraybuffer/buffer/etc) bytes of gzip file are (31, 139,   8,   0,   0,   0,   0,   0,   0,   3), thus the hex actually (safely?) can be assumed to be `0x1f8b0800000000000003`  - the rest of the hex is changing, but this is not.

**Comment by tunnckoCore** [comment]
I mean... that was easy :D

image

**Comment by tunnckoCore** [comment]
Okay, a bit more evolved, but handles gzipped raw files, and gzipped data URLs

```ts

// support ESIP-7: gzip compression
// The proposal is only for gzipped EOA creation,
// but we support gzip compression for both:
// - contracts-based creation & transfers, and
// - EOA creation & transfers
if (isGzippedInput(x.inputData)) {
  console.log("Gzipped input detected for transaction:", x.hash);

  try {
    // convert the gzipped hex into bytes
    const hexInBytes = fromHex(x.inputData, "bytes");

    // convert the gzipped bytes into the original content bytes
    const contentBytes = compress.gunzip(hexInBytes);

    // check the file type of the content bytes
    const filetypeResult = await fileTypeFromBuffer(contentBytes);

    let contentHex = "";

    // if it is a raw file gzipped, then construct a Data URL
    if (filetypeResult && filetypeResult.mime) {
      console.log("Filetype detected, transaction %s is gzipped:", x.hash, filetypeResult.mime);

      const b64 = typedArrayToBase64(contentBytes);
      const dataUrl = `data:${filetypeResult.mime};base64,${b64}`;
      contentHex = toHex(dataUrl);
    }

    // if it cannot be detected, then it is considered already a dataURL thus convert it to hex and proceed.
    else {
      // convert the original content bytes into hex
      contentHex = toHex(contentBytes);
    }

    // and replace the `inputData` with it,
    // the original hex inputData can always be found on tx.input
    x.inputData = contentHex;

    return await mapper(x);
  } catch (err) {
    console.log("Failed to decode gzipped transaction input:", x.hash, err);
  }

  return false;
}
```

**Review by RandolphJiffy — COMMENTED** [review]
great job

**Comment by RogerPodacter** [comment]
Thanks for the feedback, @tunnckoCore! To answer your questions:

> it's okay now, but also clarify in the docs, that it can actually be a gzipped data uri too, thus the detection will work like this

> detect 0x1f8b and decompress into bytes
> if the bytes decode to data uri - OK
> if the bytes show that it is actually a bare/plain file just gzipped - then consider it as data uri.

This is not correct. The bytes *must* decode to a data URI for the ethscription creation to be valid. Ethscriptions must be created with data URIs and this ESIP doesn't change that. It merely adds a processing step before the data URI is used to create an ethscription. If the bytes show that it is a bare file gzipped then it is not a valid ethscription creation.

> Also, what's the problem to be supported on contracts creation too? It's basically the same thing? Sure, contracts cannot gzip (i think?), but we usually can use contract-based creation by passing the calldata to the "mint method". Thus, we can pass gzipped data too.

It's not the same thing because the contract creation event content URI data type is a string whereas in the case of the calldata it is bytes. We could still make it work for contract creations but in evaluating this we didn't see the value; i.e., contracts emitting already-gzipped data seems rare.

We would need a compelling reason to support it because this ESIP is already a significant change. We can always add it in the future.

> Also, why not support gzipping transfers too?

Gzipping calldata transfers would be essentially gzipping random bytes which won't create savings for the user.

> (NOTE: sure, it can eventually blow up the memory somehow, right? doesn't matter if you are in a serverless environment anyway)

Yes for the implementation to be secure it must halt the decompression as soon as the 5x threshold is reached. If you wait until the end you are vulnerable to the bomb attack, though it's not clear how bad this would be in practice.

Your code has the right direction but as I mentioned above you should consider the decompressed data to be a dataURI in all cases and not do any of the `fileTypeFromBuffer` stuff.

I hope this helps!

**Comment by tunnckoCore** [comment]
@RogerPodacter 

> Gzipping calldata transfers would be essentially gzipping random bytes which won't create savings for the user.

yeah, agree, it makes sense. I just noticed that it doesn't save in size so I'll remove it.

> contracts emitting already-gzipped data seems rare. We would need a compelling reason to support it because this ESIP is already a significant change. We can always add it in the future.

I like consistency that's the main reason, and yeah it may seem rare but definitely a possibility and a good-to-have.

And yeah, definitely as a separate ESIP, for sure.

> This is not correct. The bytes must decode to a data URI for the ethscription creation to be valid. Ethscriptions must be created with data URIs and this ESIP doesn't change that. 

Yeah i know. Okay, lets focus this ESIP as just a processing step option. But should definitely think for other ESIPs. Cuz i think we can have further savings if we support raw gzipped files - we can construct the data uri and the hex, and then the flow/process is the same.

**Comment by RogerPodacter** [comment]
Sounds good!

I think if we are going to go beyond data URIs we probably have to reevaluate from scratch and do something like CBOR. Someday perhaps!

**Comment by moretarman** [comment]
Why not just use a data URI with a mime-type of application/gzip: 

data:application/gzip;base64,H4sICGtKq2UCA...

The indexer can detect the mimetype, and unzip accordingly

**Comment by RogerPodacter** [comment]
Interesting, @moretarman! This approach is actually already available and will remain available after we merge gzip, as long as clients adjust. But at the protocol-level I think it's important to give users the ability to specify "I'm sending a gzipped file" versus "I'm sending whatever and the software will take care of the compression."

This is like HTTP where you can upload a zip file to a web site but no matter what your HTTP requests should be zipped even if you don't know it.

The bigger benefit would be if we didn't require a UTF-8 data uri any longer but that would be a much bigger lift for indexers to implement.

**Comment by tunnckoCore** [comment]
> @moretarman data:application/gzip;base64,H4sICGtKq2UCA...

Problem with that is.. again, the base64-ing. Supporting raw gzipped skips this 33% from b64.

> @RogerPodacter I think if we are going to go beyond data URIs we probably have to reevaluate from scratch and do something like CBOR. 

Agree, definitely. I'm not very familiar with cbor yet. Will check it out.

**Pull request merged**
